name: build our image for latest

on:
  push:
    branches:
      - dev
      - dev-1.4

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag mhzawadi/flame:dev \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            -f .docker/Dockerfile.multiarch .
